server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: on_param
api:
  path:
    client: client
    admin: admin
springdoc:
  swagger-ui:
    path: /
logging:
  level:
    org:
      hibernate:
        type: off
spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: <login user to smtp server>
    password: <login password to smtp server>
    port: '587'
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: c##local
    url: jdbc:oracle:thin:@//localhost:1521/XE
    password: local
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
security:
  access-token:
    secret: z$C&F)J@NcRfTjWnZr4u7x!A%D*G-KaPdSgVkXp2s5v8y/B?E(H+MbQeThWmZq3t
    expires-in: 3600 #second
  refresh-token:
    secret: z$C&F)J@NcRfTjWnZr4u7x!A%D*G-KaPdSgVkXp2s5v8y/B?E(H+MbQeThWmZq3t
    expires-in: 604800 #second
  verification:
    secret:
      expires-in: 21600 #second
  recovery:
    secret:
      expires-in: 21600 #second
mail:
  from: "6051071126+ITShop@st.utc2.edu.vn"
  api-key: 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
  verification:
    template-id: d-9d313d090906406aaba2d293a1792d56
  reset-password:
    template-id: d-89ad0153d6e242b4bde9ef1d7c1fca6e
cloudinary:
  cloud-name: ddxczyxcn
  api-key: 576571749768828
  api-secret: 45-J1SFXjv_8Z0lamXOaeRjq1BE
  preset: it-shop


