insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wikivu', 8, 'ACTIVE', 1, 'Superficial frostbite of thorax, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mynte', 5, 'ACTIVE', 2, 'Displaced spiral fracture of shaft of left femur, subsequent encounter for closed fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eare', 7, 'ACTIVE', 3, 'Traumatic amputation of other parts of head');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tanoodle', 3, 'ACTIVE', 4, 'Puncture wound with foreign body of scalp, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jaxbean', 2, 'ACTIVE', 5, 'Polyhydramnios, unspecified trimester');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Cogibox', 9, 'ACTIVE', 6, 'Jumping or diving from boat striking bottom causing other injury, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mymm', 1, 'ACTIVE', 7, 'Laceration of extensor muscle, fascia and tendon of right index finger at wrist and hand level, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realbuzz', 10, 'ACTIVE', 8, 'Burn of third degree of multiple sites of unspecified lower limb, except ankle and foot, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mita', 2, 'ACTIVE', 9, 'Other congenital malformations of posterior segment of eye');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Fivechat', 7, 'ACTIVE', 10, 'Nondisplaced fracture of body of left calcaneus, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tagpad', 5, 'ACTIVE', 11, 'Other dysphagia');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mycat', 6, 'ACTIVE', 12, 'Other incomplete lesion at C4 level of cervical spinal cord, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meetz', 5, 'ACTIVE', 13, 'Displaced comminuted fracture of shaft of unspecified femur');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Oyondu', 6, 'ACTIVE', 14, 'Fracture of shoulder and upper arm');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Devcast', 7, 'ACTIVE', 15, 'Influenza due to other identified influenza virus with gastrointestinal manifestations');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mudo', 6, 'ACTIVE', 16, 'Malignant neoplasm of retromolar area');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skyvu', 8, 'ACTIVE', 17, 'Hypoxemia');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Brightdog', 8, 'ACTIVE', 18, 'Arthropathy following intestinal bypass, unspecified shoulder');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jabbertype', 3, 'ACTIVE', 19, 'Salter-Harris Type II physeal fracture of lower end of right fibula, subsequent encounter for fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yozio', 1, 'ACTIVE', 20, 'Accidental discharge and malfunction from other and unspecified firearms and guns');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Thoughtbeat', 10, 'ACTIVE', 21, 'Burn of second degree of lip(s)');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jaxspan', 4, 'ACTIVE', 22, 'Other traumatic spondylolisthesis of fifth cervical vertebra');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topicware', 5, 'ACTIVE', 23, 'Fracture of unspecified metatarsal bone(s), unspecified foot, subsequent encounter for fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Rhyzio', 9, 'ACTIVE', 24, 'Osteitis deformans of ankle and foot');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Linktype', 7, 'ACTIVE', 25, 'Displaced fracture of lower epiphysis (separation) of right femur, subsequent encounter for closed fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jamia', 8, 'ACTIVE', 26, 'Deformity of finger(s)');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Thoughtstorm', 3, 'ACTIVE', 27, 'Nondisplaced apophyseal fracture of right femur, initial encounter for open fracture type IIIA, IIIB, or IIIC');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zava', 1, 'ACTIVE', 28, 'Cutaneous leishmaniasis');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yabox', 5, 'ACTIVE', 29, 'Laceration with foreign body of right wrist, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skinder', 6, 'ACTIVE', 30, 'Displaced subtrochanteric fracture of left femur, subsequent encounter for closed fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meembee', 10, 'ACTIVE', 31, 'Pathological fracture in neoplastic disease, right hand, subsequent encounter for fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tekfly', 7, 'ACTIVE', 32, 'Pauciarticular juvenile rheumatoid arthritis, unspecified hand');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dynazzy', 2, 'ACTIVE', 33, 'Toxic effect of other metals, assault, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meemm', 10, 'ACTIVE', 34, 'Open bite of nose, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zooxo', 2, 'ACTIVE', 35, 'Displaced oblique fracture of shaft of left radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Aimbo', 9, 'ACTIVE', 36, 'Steroid responder');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tagchat', 8, 'ACTIVE', 37, 'Nondisplaced fracture (avulsion) of medial epicondyle of unspecified humerus, subsequent encounter for fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tazz', 10, 'ACTIVE', 38, 'Sprain of metacarpophalangeal joint of right thumb, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Fivechat', 9, 'ACTIVE', 39, 'Other and unspecified disorders of breast associated with pregnancy and the puerperium');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yotz', 1, 'ACTIVE', 40, 'Nondisplaced comminuted fracture of shaft of radius, right arm, subsequent encounter for closed fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Miboo', 10, 'ACTIVE', 41, 'Displaced fracture of lesser trochanter of left femur, initial encounter for open fracture type I or II');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Lazz', 9, 'ACTIVE', 42, 'Passenger on bus injured in collision with other and unspecified motor vehicles in nontraffic accident');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dazzlesphere', 4, 'ACTIVE', 43, 'Unspecified superficial injury of other fingers');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kazio', 2, 'ACTIVE', 44, 'Moderate laceration of left kidney, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eare', 8, 'ACTIVE', 45, 'Person on outside of car injured in collision with sport utility vehicle in traffic accident, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Youtags', 10, 'ACTIVE', 46, 'Lead-induced chronic gout, elbow');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Janyx', 6, 'ACTIVE', 47, 'Intravaginal torsion of spermatic cord');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skyndu', 10, 'ACTIVE', 48, 'Separation of muscle (nontraumatic), unspecified lower leg');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Aivee', 8, 'ACTIVE', 49, 'Superficial frostbite of abdominal wall, lower back and pelvis, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kaymbo', 7, 'ACTIVE', 50, 'Injury of extensor muscle, fascia and tendon of other and unspecified finger at forearm level');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skiptube', 6, 'ACTIVE', 51, 'Person on outside of other special all-terrain or other off-road motor vehicle injured in traffic accident, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('JumpXS', 7, 'ACTIVE', 52, 'Displaced fracture of middle third of navicular [scaphoid] bone of unspecified wrist, initial encounter for open fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Voolia', 4, 'ACTIVE', 53, 'Open bite of unspecified front wall of thorax with penetration into thoracic cavity, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Thoughtmix', 9, 'ACTIVE', 54, 'Varicose veins of unspecified lower extremities with pain');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Ntags', 5, 'ACTIVE', 55, 'Diphtheritic cardiomyopathy');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Centimia', 4, 'ACTIVE', 56, 'Sprain of unspecified collateral ligament of right knee');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jabbersphere', 1, 'ACTIVE', 57, 'Toxic effect of lacrimogenic gas, accidental (unintentional)');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Edgeblab', 9, 'ACTIVE', 58, 'Military operations involving accidental detonation of onboard marine weapons, military personnel');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topicblab', 7, 'ACTIVE', 59, 'Other secondary chronic gout, unspecified elbow');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eamia', 6, 'ACTIVE', 60, 'Other pre-existing diabetes mellitus in pregnancy, second trimester');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topiczoom', 4, 'ACTIVE', 61, 'Laceration of ulnar artery at wrist and hand level of left arm, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meevee', 2, 'ACTIVE', 62, 'Unspecified physeal fracture of lower end of humerus, right arm, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Leexo', 2, 'ACTIVE', 63, 'Corrosion of third degree of unspecified elbow, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mudo', 8, 'ACTIVE', 64, 'Unspecified physeal fracture of upper end of right tibia, subsequent encounter for fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Browsecat', 6, 'ACTIVE', 65, 'Pathological fracture, left ankle, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Reallinks', 6, 'ACTIVE', 66, 'Fall on board merchant ship');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Fliptune', 7, 'ACTIVE', 67, 'Unspecified injury of adductor muscle, fascia and tendon of unspecified thigh');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tambee', 1, 'ACTIVE', 68, 'Repeated falls');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Podcat', 5, 'ACTIVE', 69, '12 weeks gestation of pregnancy');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Livepath', 7, 'ACTIVE', 70, 'Fracture of unspecified part of neck of unspecified femur, initial encounter for open fracture type I or II');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yambee', 2, 'ACTIVE', 71, 'Traumatic hemorrhage of cerebrum, unspecified');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skipfire', 10, 'ACTIVE', 72, 'Unspecified fracture of upper end of unspecified humerus, initial encounter for open fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skipstorm', 10, 'ACTIVE', 73, 'Fracture of condylar process of left mandible, subsequent encounter for fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meevee', 6, 'ACTIVE', 74, 'Unspecified injury of axillary artery, right side, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Devcast', 8, 'ACTIVE', 75, 'Cannabis dependence with intoxication');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dynava', 1, 'ACTIVE', 76, 'Passenger in three-wheeled motor vehicle injured in collision with heavy transport vehicle or bus in traffic accident, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Trupe', 6, 'ACTIVE', 77, 'Unspecified car occupant injured in collision with sport utility vehicle in nontraffic accident, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Abatz', 7, 'ACTIVE', 78, 'Car driver injured in collision with pedal cycle in traffic accident');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zooxo', 7, 'ACTIVE', 79, 'Pneumonia due to Escherichia coli');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yodel', 2, 'ACTIVE', 80, 'Metabolic disorder following complete or unspecified spontaneous abortion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mynte', 9, 'ACTIVE', 81, 'Corrosion of second degree of left elbow');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twitternation', 9, 'ACTIVE', 82, 'Unspecified injury of axillary artery, right side, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Fiveclub', 6, 'ACTIVE', 83, 'Injury of popliteal artery');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Trudeo', 9, 'ACTIVE', 84, 'Unspecified subluxation of right sternoclavicular joint, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twitterbeat', 9, 'ACTIVE', 85, 'Factory as the place of occurrence of the external cause');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Browsetype', 2, 'ACTIVE', 86, 'Salter-Harris Type I physeal fracture of phalanx of unspecified toe, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realblab', 7, 'ACTIVE', 87, 'Fall in (into) bucket of water causing other injury, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Gigashots', 5, 'ACTIVE', 88, 'Other complications of anesthesia during pregnancy');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jamia', 3, 'ACTIVE', 89, 'Nondisplaced fracture of olecranon process with intraarticular extension of right ulna, subsequent encounter for closed fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Aivee', 6, 'ACTIVE', 90, 'Poisoning by macrolides, intentional self-harm, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jatri', 5, 'ACTIVE', 91, 'Breast engorgement of newborn');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Agimba', 2, 'ACTIVE', 92, 'Toxic effect of chloroform, accidental (unintentional), subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flashdog', 5, 'ACTIVE', 93, 'Stress fracture, left hand, subsequent encounter for fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kayveo', 4, 'ACTIVE', 94, 'Nondisplaced transverse fracture of shaft of left tibia, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Centizu', 8, 'ACTIVE', 95, 'Nondisplaced fracture of left radial styloid process, subsequent encounter for closed fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realcube', 2, 'ACTIVE', 96, 'Partial traumatic amputation of unspecified hip and thigh, level unspecified, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topiczoom', 5, 'ACTIVE', 97, 'Sprain of jaw, right side');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jetpulse', 9, 'ACTIVE', 98, 'Nondisplaced fracture of base of neck of right femur, subsequent encounter for closed fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Divavu', 9, 'ACTIVE', 99, 'Other physeal fracture of lower end of unspecified fibula, initial encounter for closed fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Browsebug', 4, 'ACTIVE', 100, 'Toxic effect of taipan venom, intentional self-harm');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kwimbee', 9, 'ACTIVE', 101, 'Drug or chemical induced diabetes mellitus with diabetic macular edema, resolved following treatment, left eye');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Plambee', 5, 'ACTIVE', 102, 'Maternal care for viable fetus in abdominal pregnancy, first trimester, not applicable or unspecified');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eimbee', 7, 'ACTIVE', 103, 'Salter-Harris Type IV physeal fracture of unspecified metatarsal, initial encounter for open fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoozzy', 8, 'ACTIVE', 104, 'Poisoning by, adverse effect of and underdosing of hormones and their synthetic substitutes and antagonists, not elsewhere classified');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eidel', 1, 'ACTIVE', 105, 'Unspecified injury of extensor muscle, fascia and tendon of left ring finger at wrist and hand level');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('DabZ', 6, 'ACTIVE', 106, 'Fracture of nasal bones, subsequent encounter for fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topiczoom', 6, 'ACTIVE', 107, 'Staphylococcal meningitis');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tekfly', 2, 'ACTIVE', 108, 'Contusion, laceration, and hemorrhage of cerebellum with loss of consciousness of 31 minutes to 59 minutes, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Voonte', 10, 'ACTIVE', 109, 'Retained foreign body fragments');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tavu', 7, 'ACTIVE', 110, 'Chronic maxillary sinusitis');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tagtune', 1, 'ACTIVE', 111, 'Toxic effect of hydrogen cyanide, assault');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wordpedia', 9, 'ACTIVE', 112, 'Corrosion of third degree of thumb (nail)');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vinder', 7, 'ACTIVE', 113, 'Unspecified pedal cyclist injured in collision with car, pick-up truck or van in nontraffic accident, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Oyondu', 5, 'ACTIVE', 114, 'Contusion of duodenum, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Buzzster', 10, 'ACTIVE', 115, 'Laceration of other blood vessels at hip and thigh level, right leg');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kwilith', 4, 'ACTIVE', 116, 'Displaced fracture of distal phalanx of left little finger, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realcube', 5, 'ACTIVE', 117, 'Alcohol dependence with withdrawal with perceptual disturbance');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Riffwire', 7, 'ACTIVE', 118, 'Other atherosclerosis of nonautologous biological bypass graft(s) of the extremities, right leg');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dynabox', 4, 'ACTIVE', 119, 'Underdosing of cardiac-stimulant glycosides and drugs of similar action, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Trudoo', 2, 'ACTIVE', 120, 'Puncture wound without foreign body of unspecified shoulder, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Myworks', 5, 'ACTIVE', 121, 'Newborn  affected by maternal use of drugs of addiction');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skidoo', 8, 'ACTIVE', 122, 'Superficial foreign body of unspecified parts of thorax, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twinte', 2, 'ACTIVE', 123, 'Puncture wound with foreign body of right upper arm, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twinte', 3, 'ACTIVE', 124, 'Displaced fracture of base of third metacarpal bone, right hand, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Divavu', 7, 'ACTIVE', 125, 'Hereditary deficiency of other clotting factors');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Centizu', 7, 'ACTIVE', 126, 'Poisoning by tricyclic antidepressants, accidental (unintentional)');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Bubblebox', 2, 'ACTIVE', 127, 'Other fracture of right lesser toe(s), subsequent encounter for fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Bubbletube', 9, 'ACTIVE', 128, 'Other dislocation of left shoulder joint, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vinder', 3, 'ACTIVE', 129, 'Other specified disorders of cartilage, unspecified sites');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meevee', 3, 'ACTIVE', 130, 'Poisoning by enzymes, undetermined, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Quaxo', 7, 'ACTIVE', 131, 'Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with macular edema, right eye');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jaxworks', 7, 'ACTIVE', 132, 'Intentional self-harm by other sharp object');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skynoodle', 2, 'ACTIVE', 133, 'Other group 2 peroxisomal disorders');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Gigashots', 8, 'ACTIVE', 134, 'Unspecified injury at C5 level of cervical spinal cord, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twimbo', 7, 'ACTIVE', 135, 'Fall due to controlled fire, not in building or structure, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Devshare', 5, 'ACTIVE', 136, 'Nondisplaced fracture of right radial styloid process, initial encounter for closed fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Divanoodle', 1, 'ACTIVE', 137, 'Other myelodysplastic syndromes');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topiczoom', 9, 'ACTIVE', 138, 'Testicular hypofunction');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dabjam', 9, 'ACTIVE', 139, 'Driver of heavy transport vehicle injured in noncollision transport accident in traffic accident, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Centimia', 8, 'ACTIVE', 140, 'Poisoning by, adverse effect of and underdosing of antidiarrheal drugs');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yakidoo', 10, 'ACTIVE', 141, 'Poisoning by other drug primarily affecting the autonomic nervous system, assault, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Demivee', 10, 'ACTIVE', 142, 'Other mechanical complication of unspecified internal joint prosthesis, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Aimbu', 8, 'ACTIVE', 143, 'Unspecified malignant neoplasm of skin of unspecified ear and external auricular canal');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flipopia', 1, 'ACTIVE', 144, 'Coronary artery aneurysm');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoonder', 4, 'ACTIVE', 145, 'Animal-rider or occupant of animal-drawn vehicle injured in collision with car, pick-up truck, van, heavy transport vehicle or bus');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Lazzy', 10, 'ACTIVE', 146, 'Laceration of unspecified tibial artery, right leg, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topicstorm', 10, 'ACTIVE', 147, 'Laceration of fallopian tube, unspecified');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Podcat', 4, 'ACTIVE', 148, 'Fistula, unspecified elbow');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meevee', 9, 'ACTIVE', 149, 'Traumatic hemorrhage of cerebrum, unspecified, with loss of consciousness of 6 hours to 24 hours, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flipbug', 5, 'ACTIVE', 150, 'Lobster-claw hand, bilateral');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Quinu', 9, 'ACTIVE', 151, 'Driver of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle in nontraffic accident, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jayo', 2, 'ACTIVE', 152, 'Embedded teeth');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twitterlist', 4, 'ACTIVE', 153, 'Blood alcohol level of 200-239 mg/100 ml');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Shufflebeat', 9, 'ACTIVE', 154, 'Person boarding or alighting a three-wheeled motor vehicle injured in collision with pedal cycle');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Linklinks', 1, 'ACTIVE', 155, 'Other displaced fracture of base of first metacarpal bone, right hand, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flipbug', 5, 'ACTIVE', 156, 'Contusion of knee');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twitterlist', 10, 'ACTIVE', 157, 'Torus fracture of lower end of right radius, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tanoodle', 6, 'ACTIVE', 158, 'Terrorism involving other means, public safety official injured, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dynava', 5, 'ACTIVE', 159, 'Congenital lordosis, sacral and sacrococcygeal region');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Oodoo', 9, 'ACTIVE', 160, 'Salter-Harris Type IV physeal fracture of phalanx of right toe, subsequent encounter for fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Teklist', 9, 'ACTIVE', 161, 'Laceration of popliteal artery, unspecified leg, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Quire', 8, 'ACTIVE', 162, 'Nondisplaced oblique fracture of shaft of humerus, unspecified arm, initial encounter for open fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flashset', 9, 'ACTIVE', 163, 'Pathological fracture in neoplastic disease, unspecified foot, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Rhyloo', 5, 'ACTIVE', 164, 'Obstruction due to foreign body accidentally left in body following aspiration, puncture or other catheterization, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kare', 8, 'ACTIVE', 165, 'Driver of three-wheeled motor vehicle injured in collision with other motor vehicles in nontraffic accident, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jatri', 2, 'ACTIVE', 166, 'Other specified disorders of amniotic fluid and membranes');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Quimm', 8, 'ACTIVE', 167, 'Unspecified fracture of first metacarpal bone, right hand, initial encounter for closed fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Ozu', 10, 'ACTIVE', 168, 'Unspecified fracture of upper end of right ulna, subsequent encounter for open fracture type I or II with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meezzy', 7, 'ACTIVE', 169, 'Puncture wound without foreign body of other specified part of neck, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoombox', 9, 'ACTIVE', 170, 'Inhalant abuse with inhalant-induced psychotic disorder, unspecified');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Chatterpoint', 1, 'ACTIVE', 171, 'Open bite of right thumb with damage to nail, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jabberbean', 7, 'ACTIVE', 172, 'Preterm premature rupture of membranes, unspecified as to length of time between rupture and onset of labor, unspecified trimester');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Voomm', 10, 'ACTIVE', 173, 'Contact with power take-off devices (PTO), initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Oyondu', 6, 'ACTIVE', 174, 'Unspecified fracture of T9-T10 vertebra');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yotz', 8, 'ACTIVE', 175, 'Postprocedural hemorrhage of a digestive system organ or structure following other procedure');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Gigaclub', 3, 'ACTIVE', 176, 'Chronic pulmonary insufficiency following surgery');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Katz', 7, 'ACTIVE', 177, 'Other injury of other muscle(s) and tendon(s) at lower leg level, left leg');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vidoo', 1, 'ACTIVE', 178, 'Embolism due to cardiac prosthetic devices, implants and grafts, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yombu', 8, 'ACTIVE', 179, 'Twin pregnancy, dichorionic/diamniotic, second trimester');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skimia', 10, 'ACTIVE', 180, 'Exposure of graft of urinary organ, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Thoughtmix', 4, 'ACTIVE', 181, 'Toxic effect of nitrogen oxides, undetermined, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eire', 1, 'ACTIVE', 182, 'Trichomonal vulvovaginitis');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Buzzster', 3, 'ACTIVE', 183, 'Toxic maculopathy, bilateral');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jaxbean', 8, 'ACTIVE', 184, 'Toxic effect of venom of centipedes and venomous millipedes, intentional self-harm, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Talane', 6, 'ACTIVE', 185, 'Worries');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kwilith', 2, 'ACTIVE', 186, 'Glider (nonpowered) crash injuring occupant, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Npath', 9, 'ACTIVE', 187, 'Displaced fracture of coronoid process of left ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vidoo', 1, 'ACTIVE', 188, 'Muscle wasting and atrophy, not elsewhere classified, unspecified hand');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skyvu', 3, 'ACTIVE', 189, 'Rheumatoid nodule, right ankle and foot');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skiba', 6, 'ACTIVE', 190, 'Adverse effect of emetics, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Shuffletag', 7, 'ACTIVE', 191, 'Influenza due to identified novel influenza A virus with other manifestations');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Thoughtstorm', 9, 'ACTIVE', 192, 'Toxic effect of hydrogen cyanide, intentional self-harm, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realcube', 10, 'ACTIVE', 193, 'Unspecified nondisplaced fracture of surgical neck of right humerus, subsequent encounter for fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vipe', 4, 'ACTIVE', 194, 'Passenger on bus injured in collision with pedestrian or animal in nontraffic accident, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wikibox', 1, 'ACTIVE', 195, 'Retinal neovascularization, unspecified, right eye');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wikido', 6, 'ACTIVE', 196, 'Nondisplaced fracture of lateral malleolus of unspecified fibula, subsequent encounter for open fracture type I or II with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Roodel', 8, 'ACTIVE', 197, 'Burn of first degree of thumb (nail)');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Trilith', 9, 'ACTIVE', 198, 'Nondisplaced fracture of shaft of fifth metacarpal bone, left hand, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yozio', 7, 'ACTIVE', 199, 'Unspecified displaced fracture of third cervical vertebra, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Innojam', 1, 'ACTIVE', 200, 'External constriction of toe');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kwilith', 9, 'ACTIVE', 201, 'Poisoning by salicylates, undetermined, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoomlounge', 10, 'ACTIVE', 202, 'Laceration with foreign body of abdominal wall, right upper quadrant with penetration into peritoneal cavity');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realcube', 6, 'ACTIVE', 203, 'Acute suppurative otitis media without spontaneous rupture of ear drum, bilateral');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Npath', 3, 'ACTIVE', 204, 'Asphyxiation due to hanging, undetermined');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Livefish', 7, 'ACTIVE', 205, 'Postprocedural pneumothorax');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tazz', 2, 'ACTIVE', 206, 'Other injury of muscle, fascia and tendon of long head of biceps');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Thoughtsphere', 9, 'ACTIVE', 207, 'Unspecified physeal fracture of upper end of right femur, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kayveo', 4, 'ACTIVE', 208, 'Other shellfish poisoning, intentional self-harm');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yakijo', 10, 'ACTIVE', 209, 'Tinea nigra');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dabtype', 8, 'ACTIVE', 210, 'Crushing injury of hip with thigh');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Camido', 4, 'ACTIVE', 211, 'Laceration of flexor muscle, fascia and tendon of right index finger at forearm level, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Bluejam', 9, 'ACTIVE', 212, 'Displaced comminuted fracture of shaft of unspecified tibia, initial encounter for open fracture type I or II');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Trilia', 6, 'ACTIVE', 213, 'Moderate laceration of tail of pancreas, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoonoodle', 3, 'ACTIVE', 214, 'Burn of third degree of unspecified hand, unspecified site, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Babbleset', 10, 'ACTIVE', 215, 'Nondisplaced transverse fracture of unspecified patella, subsequent encounter for open fracture type I or II with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eazzy', 1, 'ACTIVE', 216, 'Nondisplaced transverse fracture of shaft of right tibia');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Pixoboo', 1, 'ACTIVE', 217, 'Unspecified superficial injury of right elbow');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Photojam', 4, 'ACTIVE', 218, 'Toxoplasma chorioretinitis');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kare', 4, 'ACTIVE', 219, 'Other acquired stenosis of right external ear canal');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dynabox', 5, 'ACTIVE', 220, 'Injury of unspecified nerve at wrist and hand level');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skyndu', 9, 'ACTIVE', 221, 'Type 2 diabetes mellitus with severe nonproliferative diabetic retinopathy with macular edema, unspecified eye');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Voonte', 8, 'ACTIVE', 222, 'Sprain of medial collateral ligament of right knee, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Rhynyx', 3, 'ACTIVE', 223, 'Blister (nonthermal) of left ear, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Demivee', 10, 'ACTIVE', 224, 'Unspecified physeal fracture of unspecified metatarsal, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Aimbo', 8, 'ACTIVE', 225, 'Unspecified injury of other blood vessels at wrist and hand level of unspecified arm, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dabvine', 5, 'ACTIVE', 226, 'Laceration of unspecified muscle, fascia and tendon at wrist and hand level, left hand');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mita', 9, 'ACTIVE', 227, 'Corrosion of first degree of neck, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yotz', 5, 'ACTIVE', 228, 'Pathological fracture in other disease, hip, unspecified, subsequent encounter for fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Photospace', 6, 'ACTIVE', 229, 'Other postprocedural endocrine and metabolic complications and disorders');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realfire', 9, 'ACTIVE', 230, 'Injury of nerve root of cervical spine, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topicstorm', 10, 'ACTIVE', 231, 'Drowning and submersion due to other accident to other powered watercraft, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wordtune', 3, 'ACTIVE', 232, 'Displaced fracture of medial phalanx of left middle finger, subsequent encounter for fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kwideo', 1, 'ACTIVE', 233, 'Toxic effect of latex, assault');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Blognation', 9, 'ACTIVE', 234, 'Chimera 46, XX/46, XY');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dabvine', 8, 'ACTIVE', 235, 'Adverse effect of other nonopioid analgesics and antipyretics, not elsewhere classified, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dablist', 10, 'ACTIVE', 236, 'Partial traumatic metacarpophalangeal amputation of right middle finger, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Viva', 3, 'ACTIVE', 237, 'Other osteoporosis with current pathological fracture, unspecified hand, subsequent encounter for fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Centidel', 7, 'ACTIVE', 238, 'Major laceration of greater saphenous vein at hip and thigh level, unspecified leg, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realbridge', 3, 'ACTIVE', 239, 'Other specified hearing loss');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Youspan', 6, 'ACTIVE', 240, 'Open bite of left front wall of thorax without penetration into thoracic cavity, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twitternation', 1, 'ACTIVE', 241, 'Puncture wound with foreign body of nose');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jamia', 3, 'ACTIVE', 242, 'War operation involving nuclear radiation effects of nuclear weapon, military personnel');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jabbercube', 8, 'ACTIVE', 243, 'Toxic effect of strychnine and its salts, intentional self-harm, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jaloo', 2, 'ACTIVE', 244, 'Poisoning by heroin, intentional self-harm, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vinder', 6, 'ACTIVE', 245, 'Alveolar proteinosis');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twiyo', 9, 'ACTIVE', 246, 'Accidental drowning and submersion while in bath-tub, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Leenti', 3, 'ACTIVE', 247, 'Assault by being hit or run over by motor vehicle');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skyble', 2, 'ACTIVE', 248, 'Other intraarticular fracture of lower end of radius');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Roombo', 1, 'ACTIVE', 249, 'Burn of second degree of right axilla, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skaboo', 5, 'ACTIVE', 250, 'Phlebitis and thrombophlebitis of right femoral vein');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skidoo', 3, 'ACTIVE', 251, 'Toxic effect of carbon monoxide from utility gas, assault');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flashdog', 7, 'ACTIVE', 252, 'Displaced fracture of proximal phalanx of left lesser toe(s), initial encounter for open fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Pixope', 7, 'ACTIVE', 253, 'Laceration of unspecified quadriceps muscle, fascia and tendon, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Riffpedia', 5, 'ACTIVE', 254, 'Stable burst fracture of second lumbar vertebra');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topicstorm', 3, 'ACTIVE', 255, 'Other fractures of lower end of left radius, subsequent encounter for open fracture type I or II with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Katz', 3, 'ACTIVE', 256, 'Strain of intrinsic muscle, fascia and tendon of right thumb at wrist and hand level, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eabox', 6, 'ACTIVE', 257, 'Underdosing of local antifungal, anti-infective and anti-inflammatory drugs, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Gabcube', 4, 'ACTIVE', 258, 'Recurrent dislocation, left hip');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Ozu', 1, 'ACTIVE', 259, 'Injury of acoustic nerve, unspecified side, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dynazzy', 5, 'ACTIVE', 260, 'Recurrent dislocation, left wrist');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Devshare', 2, 'ACTIVE', 261, 'Displaced intertrochanteric fracture of left femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Avaveo', 9, 'ACTIVE', 262, 'Unspecified fracture of patella');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topicstorm', 10, 'ACTIVE', 263, 'Arthropathies in other specified diseases classified elsewhere, unspecified shoulder');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yambee', 9, 'ACTIVE', 264, 'Nondisplaced transverse fracture of right patella, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Fliptune', 9, 'ACTIVE', 265, 'Unspecified injury of urethra');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Centimia', 4, 'ACTIVE', 266, 'Other dislocation of left wrist and hand');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jayo', 1, 'ACTIVE', 267, 'Adverse effect of unspecified psychotropic drug, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Devpoint', 10, 'ACTIVE', 268, 'Superficial frostbite of unspecified sites, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Trupe', 1, 'ACTIVE', 269, 'Traumatic rupture of volar plate of right middle finger at metacarpophalangeal and interphalangeal joint, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Janyx', 3, 'ACTIVE', 270, 'Encephalitis, myelitis and encephalomyelitis, unspecified');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wikido', 9, 'ACTIVE', 271, 'Velamentous insertion of umbilical cord');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Quimm', 7, 'ACTIVE', 272, 'Laceration of muscle and tendon of front wall of thorax, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Viva', 8, 'ACTIVE', 273, 'Unspecified fracture of lower end of right tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Photospace', 4, 'ACTIVE', 274, 'Carcinoma in situ of other and unspecified male genital organs');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Youtags', 6, 'ACTIVE', 275, 'Burn of third degree of male genital region');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoomzone', 4, 'ACTIVE', 276, 'Nodular sclerosis Hodgkin lymphoma, spleen');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zazio', 4, 'ACTIVE', 277, 'Nondisplaced fracture of base of fifth metacarpal bone. left hand, subsequent encounter for fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Feedspan', 5, 'ACTIVE', 278, 'Acquired atrophy of left ovary and fallopian tube');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Brightdog', 9, 'ACTIVE', 279, 'Laceration with foreign body of left breast, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Teklist', 6, 'ACTIVE', 280, 'Unspecified trochanteric fracture of right femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realpoint', 6, 'ACTIVE', 281, 'Unspecified fracture of head of unspecified femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Izio', 9, 'ACTIVE', 282, 'War operations involving combat using blunt or piercing object, civilian, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Agimba', 6, 'ACTIVE', 283, 'Puncture wound with foreign body of abdominal wall, epigastric region with penetration into peritoneal cavity, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realmix', 4, 'ACTIVE', 284, 'Nondisplaced oblique fracture of shaft of humerus, right arm, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Youspan', 2, 'ACTIVE', 285, 'Other benign neoplasm of skin of other and unspecified parts of face');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Feedbug', 6, 'ACTIVE', 286, 'Other ectopic pregnancy with intrauterine pregnancy');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mita', 2, 'ACTIVE', 287, 'Strain of extensor muscle, fascia and tendon of unspecified thumb at wrist and hand level, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jabbersphere', 9, 'ACTIVE', 288, 'Laceration of extensor muscle, fascia and tendon of unspecified thumb at wrist and hand level, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jaloo', 5, 'ACTIVE', 289, 'Injury of right iliac vein, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wikivu', 4, 'ACTIVE', 290, 'Injury of other nerves at hip and thigh level, right leg, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dazzlesphere', 2, 'ACTIVE', 291, 'Charcot''s joint, unspecified hip');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eimbee', 6, 'ACTIVE', 292, 'Strain of right quadriceps muscle, fascia and tendon');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Brainbox', 6, 'ACTIVE', 293, 'Flexion deformity, finger joints');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Camimbo', 5, 'ACTIVE', 294, 'Laceration of dorsal artery of right foot, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mybuzz', 8, 'ACTIVE', 295, 'Other specified fracture of right pubis, initial encounter for open fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Camido', 8, 'ACTIVE', 296, 'Nondisplaced bimalleolar fracture of unspecified lower leg, subsequent encounter for closed fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dabshots', 7, 'ACTIVE', 297, 'Fracture of bone following insertion of orthopedic implant, joint prosthesis, or bone plate');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realcube', 6, 'ACTIVE', 298, 'War operations involving explosion of torpedo');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Quaxo', 5, 'ACTIVE', 299, 'Displaced transverse fracture of shaft of right femur, subsequent encounter for closed fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vitz', 6, 'ACTIVE', 300, 'Breakdown (mechanical) of heart valve prosthesis, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Brainbox', 7, 'ACTIVE', 301, 'Laceration with foreign body, unspecified foot');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Blogtag', 9, 'ACTIVE', 302, 'Non-pressure chronic ulcer of other part of left foot');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Quinu', 3, 'ACTIVE', 303, 'Insect bite (nonvenomous) of other finger, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Plambee', 10, 'ACTIVE', 304, 'Pedestrian on foot injured in collision with heavy transport vehicle or bus, unspecified whether traffic or nontraffic accident, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eadel', 1, 'ACTIVE', 305, 'Ciguatera fish poisoning, accidental (unintentional), subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twitterbeat', 4, 'ACTIVE', 306, 'Maternal care for high head at term, fetus 3');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mynte', 6, 'ACTIVE', 307, 'Effect of reduced temperature, unspecified');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flashset', 5, 'ACTIVE', 308, 'Nondisplaced transverse fracture of right patella, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dablist', 7, 'ACTIVE', 309, 'Military operations involving other explosions and fragments, civilian, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yodoo', 6, 'ACTIVE', 310, 'Displaced unspecified condyle fracture of lower end of right femur, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Aimbo', 8, 'ACTIVE', 311, 'Injury of other nerves at forearm level, unspecified arm, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Rhynoodle', 7, 'ACTIVE', 312, 'Intentional self-harm by drowning and submersion in natural water, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Youbridge', 2, 'ACTIVE', 313, 'Burn of second degree of forehead and cheek');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Innotype', 4, 'ACTIVE', 314, 'Person on outside of car injured in collision with other nonmotor vehicle in traffic accident, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('InnoZ', 1, 'ACTIVE', 315, 'Nondisplaced fracture of capitate [os magnum] bone, left wrist, subsequent encounter for fracture with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Voomm', 2, 'ACTIVE', 316, 'Toxic erythema');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flipstorm', 7, 'ACTIVE', 317, 'Burn of second degree of shoulder');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skipstorm', 9, 'ACTIVE', 318, 'Cardiac arrest following an ectopic and molar pregnancy');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topicblab', 10, 'ACTIVE', 319, 'Encounter for supervision of normal first pregnancy');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Edgewire', 8, 'ACTIVE', 320, 'Cutaneous T-cell lymphoma, unspecified, spleen');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Minyx', 8, 'ACTIVE', 321, 'Poisoning by unspecified drugs primarily affecting the autonomic nervous system, undetermined, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jayo', 6, 'ACTIVE', 322, 'Atrophy of globe, right eye');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Devpoint', 10, 'ACTIVE', 323, 'Exudative age-related macular degeneration, bilateral');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Babbleblab', 4, 'ACTIVE', 324, 'Other private fixed-wing aircraft explosion injuring occupant');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wikizz', 6, 'ACTIVE', 325, 'Other congenital malformations of urinary system');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meemm', 4, 'ACTIVE', 326, 'Laceration of abdominal wall with foreign body, periumbilic region without penetration into peritoneal cavity, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Aivee', 3, 'ACTIVE', 327, 'Acute monoblastic/monocytic leukemia, in remission');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Rhynoodle', 4, 'ACTIVE', 328, 'Walked into furniture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Muxo', 6, 'ACTIVE', 329, 'Minor laceration of left external jugular vein');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Blogspan', 10, 'ACTIVE', 330, 'Chronic serous otitis media, right ear');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jabbersphere', 1, 'ACTIVE', 331, 'Injury of trochlear nerve, left side, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realfire', 5, 'ACTIVE', 332, 'Other chronic osteomyelitis, right shoulder');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wikizz', 6, 'ACTIVE', 333, 'Other specified injuries of other specified part of neck');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twinte', 5, 'ACTIVE', 334, 'Displaced fracture of neck of right radius, subsequent encounter for open fracture type I or II with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Bluejam', 6, 'ACTIVE', 335, 'Adverse effect of electrolytic, caloric and water-balance agents, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Digitube', 8, 'ACTIVE', 336, 'Salter-Harris Type III physeal fracture of unspecified calcaneus, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Browsezoom', 8, 'ACTIVE', 337, 'Acute angle-closure glaucoma, left eye');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Centizu', 7, 'ACTIVE', 338, 'Unspecified occupant of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle in nontraffic accident');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Browsezoom', 7, 'ACTIVE', 339, 'Other fracture of lower end of left tibia, subsequent encounter for open fracture type I or II with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Feedmix', 7, 'ACTIVE', 340, 'Other congenital malformation syndromes with other skeletal changes');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Ntags', 8, 'ACTIVE', 341, 'Crushing injury of unspecified lower leg, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('InnoZ', 5, 'ACTIVE', 342, 'Displaced oblique fracture of shaft of left femur, subsequent encounter for open fracture type I or II with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mynte', 1, 'ACTIVE', 343, 'Puncture wound without foreign body of left middle finger without damage to nail');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Oba', 7, 'ACTIVE', 344, 'Crushed by other nonvenomous reptiles, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Chatterbridge', 6, 'ACTIVE', 345, 'Other atrophic disorders of skin');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Gabtune', 1, 'ACTIVE', 346, 'Acquired deformity of pinna, left ear');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Chatterpoint', 8, 'ACTIVE', 347, 'Blister (nonthermal), left lower leg, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flipstorm', 7, 'ACTIVE', 348, 'Nondisplaced fracture of head of unspecified radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Avamm', 4, 'ACTIVE', 349, 'External constriction of part of breast, unspecified breast, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Katz', 5, 'ACTIVE', 350, 'Pedestrian on roller-skates injured in collision with other nonmotor vehicle in traffic accident, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kazio', 6, 'ACTIVE', 351, 'Increased secretion of glucagon');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yodo', 4, 'ACTIVE', 352, 'Malignant neoplasm of colon, unspecified');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jayo', 7, 'ACTIVE', 353, 'Counseling related to combined concerns regarding sexual attitude, behavior and orientation');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Izio', 6, 'ACTIVE', 354, 'Central cord syndrome at C3 level of cervical spinal cord, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Fiveclub', 7, 'ACTIVE', 355, 'Osseous obstruction of Eustachian tube, unspecified ear');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jayo', 5, 'ACTIVE', 356, 'Nondisplaced transverse fracture of shaft of unspecified radius, subsequent encounter for open fracture type I or II with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Midel', 9, 'ACTIVE', 357, 'Other firearm discharge, undetermined intent, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Photojam', 5, 'ACTIVE', 358, 'Traumatic hemorrhage of left cerebrum with loss of consciousness of 1 hours to 5 hours 59 minutes, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vinte', 8, 'ACTIVE', 359, 'Corneal degeneration');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Photospace', 2, 'ACTIVE', 360, 'Coma scale, eyes open, never, 24 hours or more after hospital admission');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skyba', 4, 'ACTIVE', 361, 'Other sprain of right ring finger');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realcube', 2, 'ACTIVE', 362, 'Displaced simple supracondylar fracture without intercondylar fracture of unspecified humerus, subsequent encounter for fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Trudeo', 1, 'ACTIVE', 363, 'Person on outside of pick-up truck or van injured in collision with pedestrian or animal in traffic accident, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Voonte', 10, 'ACTIVE', 364, 'Unspecified nondisplaced fracture of surgical neck of left humerus, initial encounter for closed fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Oloo', 1, 'ACTIVE', 365, 'Cerebral infarction due to thrombosis of unspecified middle cerebral artery');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Rhyzio', 9, 'ACTIVE', 366, 'Unspecified dislocation of right knee, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twitterwire', 4, 'ACTIVE', 367, 'Other chronic hematogenous osteomyelitis, right ankle and foot');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Feednation', 8, 'ACTIVE', 368, 'Poisoning by cardiac-stimulant glycosides and drugs of similar action, undetermined');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Shuffletag', 4, 'ACTIVE', 369, 'Displaced spiral fracture of shaft of right femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tambee', 1, 'ACTIVE', 370, 'Deficiency of vitamin K');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Photolist', 4, 'ACTIVE', 371, 'Poisoning by anticholinesterase agents, undetermined');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zooveo', 8, 'ACTIVE', 372, 'Forced landing of other private fixed-wing aircraft injuring occupant, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mydeo', 3, 'ACTIVE', 373, 'Blister (nonthermal) of unspecified front wall of thorax');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Camido', 3, 'ACTIVE', 374, 'Poisoning by carbonic-anhydrase inhibitors, benzothiadiazides and other diuretics, accidental (unintentional), subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Youbridge', 6, 'ACTIVE', 375, 'Motorcycle driver injured in noncollision transport accident in nontraffic accident, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Blognation', 3, 'ACTIVE', 376, 'Corrosion of second degree of left shoulder');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Photobug', 3, 'ACTIVE', 377, 'Unspecified injury of shoulder and upper arm, unspecified arm, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Agimba', 4, 'ACTIVE', 378, 'Major laceration of unspecified internal jugular vein, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realcube', 5, 'ACTIVE', 379, 'Other ocular albinism');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Livetube', 6, 'ACTIVE', 380, 'Displaced longitudinal fracture of right patella, subsequent encounter for closed fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jetpulse', 1, 'ACTIVE', 381, 'Type O blood, Rh negative');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vinte', 8, 'ACTIVE', 382, 'Corrosion of unspecified degree of left upper arm, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mudo', 10, 'ACTIVE', 383, 'Other fracture of shaft of unspecified tibia, initial encounter for open fracture type IIIA, IIIB, or IIIC');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Rooxo', 4, 'ACTIVE', 384, 'Hit by object from burning building or structure in controlled fire');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kanoodle', 3, 'ACTIVE', 385, 'Injury of accessory nerve, left side, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Brainverse', 4, 'ACTIVE', 386, 'Burn of third degree of single right finger (nail) except thumb');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Voolia', 5, 'ACTIVE', 387, 'Diffuse traumatic brain injury with loss of consciousness of unspecified duration, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yakitri', 1, 'ACTIVE', 388, 'Displacement of internal fixation device of bone of left lower leg, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Oyoloo', 8, 'ACTIVE', 389, 'Neuromuscular scoliosis, thoracic region');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Devcast', 2, 'ACTIVE', 390, 'Maternal care for hydrops fetalis, first trimester, fetus 3');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kwimbee', 5, 'ACTIVE', 391, 'Nondisplaced fracture of shaft of left clavicle, subsequent encounter for fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wikizz', 8, 'ACTIVE', 392, 'Pulmonary anthrax');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Katz', 10, 'ACTIVE', 393, 'Burn of third degree of multiple left fingers (nail), including thumb, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topicshots', 1, 'ACTIVE', 394, 'Unspecified occupant of three-wheeled motor vehicle injured in collision with unspecified motor vehicles in nontraffic accident');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kimia', 1, 'ACTIVE', 395, 'Nondisplaced transverse fracture of shaft of left fibula, initial encounter for open fracture type IIIA, IIIB, or IIIC');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoonoodle', 8, 'ACTIVE', 396, 'Burn of first degree of lower limb, except ankle and foot');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Katz', 10, 'ACTIVE', 397, 'Nondisplaced fracture of anterior process of unspecified calcaneus, initial encounter for closed fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Gigabox', 3, 'ACTIVE', 398, 'Animal-rider injured in unspecified transport accident, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dynava', 2, 'ACTIVE', 399, 'Medial dislocation of proximal end of tibia, right knee, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoombeat', 6, 'ACTIVE', 400, 'Unspecified disorder of synovium and tendon, forearm');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Ntag', 5, 'ACTIVE', 401, 'Congenital pneumonia due to streptococcus, group B');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Brainsphere', 10, 'ACTIVE', 402, 'Unspecified injury of blood vessel of left ring finger, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Gevee', 4, 'ACTIVE', 403, 'Crushing injury of left ankle, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Reallinks', 1, 'ACTIVE', 404, 'Anthrax');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flashspan', 10, 'ACTIVE', 405, 'Underdosing of other parasympatholytics [anticholinergics and antimuscarinics] and spasmolytics, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Aimbo', 5, 'ACTIVE', 406, 'Unspecified injury of extensor muscle, fascia and tendon of other finger at wrist and hand level');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Shufflebeat', 9, 'ACTIVE', 407, 'Fracture of symphysis of mandible, initial encounter for closed fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Fatz', 6, 'ACTIVE', 408, 'Nondisplaced oblique fracture of shaft of left radius, subsequent encounter for open fracture type I or II with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Youopia', 9, 'ACTIVE', 409, 'Nondisplaced spiral fracture of shaft of humerus, unspecified arm, subsequent encounter for fracture with delayed healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Avamba', 5, 'ACTIVE', 410, 'Unspecified blood type');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mydeo', 4, 'ACTIVE', 411, 'Sprain of interphalangeal joint of right lesser toe(s), initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Browsetype', 6, 'ACTIVE', 412, 'Menopausal and other perimenopausal disorders');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twitternation', 6, 'ACTIVE', 413, 'War operations involving indirect blast effect of nuclear weapon, civilian, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eare', 4, 'ACTIVE', 414, 'Displaced fracture of base of neck of right femur, subsequent encounter for open fracture type I or II with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Avamm', 9, 'ACTIVE', 415, 'Recurrent isolated sleep paralysis');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Youbridge', 1, 'ACTIVE', 416, 'Laceration of dorsal vein of left foot');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twitterwire', 4, 'ACTIVE', 417, 'Other dislocation of unspecified wrist and hand, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Browsezoom', 2, 'ACTIVE', 418, 'Intra-abdominal and pelvic swelling, mass and lump, unspecified site');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flipbug', 5, 'ACTIVE', 419, 'Jumping or diving from boat striking bottom causing drowning and submersion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Minyx', 4, 'ACTIVE', 420, 'Posterior dislocation of left hip, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Latz', 6, 'ACTIVE', 421, 'Longitudinal fracture of patella');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tambee', 9, 'ACTIVE', 422, 'Other specified diseases of pancreas');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Brainsphere', 7, 'ACTIVE', 423, 'Underdosing of predominantly beta-adrenoreceptor agonists, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Ainyx', 2, 'ACTIVE', 424, 'Passenger in heavy transport vehicle injured in collision with heavy transport vehicle or bus in nontraffic accident, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Youspan', 2, 'ACTIVE', 425, 'Burn of unspecified degree of right palm, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Viva', 10, 'ACTIVE', 426, 'Pedestrian on skateboard injured in collision with railway train or railway vehicle in nontraffic accident');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Einti', 5, 'ACTIVE', 427, 'Toxic effect of cobra venom, undetermined, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mymm', 7, 'ACTIVE', 428, 'Other specified injury of long flexor muscle, fascia and tendon of left thumb at wrist and hand level, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Devpulse', 8, 'ACTIVE', 429, 'Pedal cycle passenger injured in collision with other nonmotor vehicle in nontraffic accident, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twinte', 10, 'ACTIVE', 430, 'Hypomagnesemia');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realmix', 3, 'ACTIVE', 431, 'Burn of third degree of left hand, unspecified site, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mynte', 9, 'ACTIVE', 432, 'Nondisplaced fracture of base of second metacarpal bone. left hand, initial encounter for open fracture');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yakidoo', 3, 'ACTIVE', 433, 'Abrasion of lip');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skibox', 9, 'ACTIVE', 434, 'Injury of lateral plantar nerve, right leg, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dazzlesphere', 10, 'ACTIVE', 435, 'Poisoning by iron and its compounds, accidental (unintentional), subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Lajo', 3, 'ACTIVE', 436, 'Unspecified adult maltreatment, confirmed');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jabbersphere', 4, 'ACTIVE', 437, 'Arthropathies in other specified diseases classified elsewhere');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Wordpedia', 8, 'ACTIVE', 438, 'Malignant neoplasm of left renal pelvis');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Buzzdog', 10, 'ACTIVE', 439, 'Complete traumatic amputation at unspecified shoulder joint, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Vinder', 6, 'ACTIVE', 440, 'Strain of other flexor muscle, fascia and tendon at forearm level, unspecified arm, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Flipstorm', 1, 'ACTIVE', 441, 'Partial traumatic amputation at level between right shoulder and elbow, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Pixoboo', 7, 'ACTIVE', 442, 'Adverse effect of insulin and oral hypoglycemic [antidiabetic] drugs, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Voomm', 6, 'ACTIVE', 443, 'Person boarding or alighting a pedal cycle injured in noncollision transport accident, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Bubbletube', 3, 'ACTIVE', 444, 'Impacted teeth');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Fanoodle', 7, 'ACTIVE', 445, 'Retained foreign body fragments, unspecified material');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tagpad', 9, 'ACTIVE', 446, 'Driver of heavy transport vehicle injured in collision with heavy transport vehicle or bus in nontraffic accident, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Linkbuzz', 8, 'ACTIVE', 447, 'Laceration without foreign body of unspecified lesser toe(s) without damage to nail');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Einti', 1, 'ACTIVE', 448, 'Other displaced fracture of base of first metacarpal bone, right hand, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Leexo', 5, 'ACTIVE', 449, 'Displaced fracture of lateral condyle of right tibia, subsequent encounter for closed fracture with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('JumpXS', 1, 'ACTIVE', 450, 'Encounter for screening for malignant neoplasm of small intestine');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Topicblab', 4, 'ACTIVE', 451, 'Other atherosclerosis of nonbiological bypass graft(s) of the extremities');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Linklinks', 7, 'ACTIVE', 452, 'Cervical disc disorder with myelopathy, mid-cervical region');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Oyope', 7, 'ACTIVE', 453, 'Drug or chemical induced diabetes mellitus with diabetic macular edema, resolved following treatment');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Bubblebox', 1, 'ACTIVE', 454, 'Puncture wound with foreign body of right cheek and temporomandibular area, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tavu', 1, 'ACTIVE', 455, 'Drowning and submersion due to fall off canoe or kayak, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tambee', 1, 'ACTIVE', 456, 'Other fracture of shaft of radius, left arm, subsequent encounter for closed fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoombox', 2, 'ACTIVE', 457, 'Contact with liquid air, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realpoint', 9, 'ACTIVE', 458, 'Burn of third degree of shoulder');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skibox', 2, 'ACTIVE', 459, 'Benign neoplasm of other specified parts of central nervous system');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Twimbo', 8, 'ACTIVE', 460, 'Laceration of other specified intrathoracic organs, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Livetube', 7, 'ACTIVE', 461, 'Person on outside of three-wheeled motor vehicle injured in collision with two- or three-wheeled motor vehicle in traffic accident');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Eire', 2, 'ACTIVE', 462, 'Fall on or from playground slide, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Buzzbean', 5, 'ACTIVE', 463, 'Burn of second degree of unspecified multiple fingers (nail), including thumb, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Roodel', 6, 'ACTIVE', 464, 'Salter-Harris Type III physeal fracture of lower end of humerus, left arm, subsequent encounter for fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dabfeed', 10, 'ACTIVE', 465, 'Recurrent dislocation, unspecified wrist');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Yabox', 8, 'ACTIVE', 466, 'Other specified injury of unspecified blood vessel at wrist and hand of right arm, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Dabjam', 6, 'ACTIVE', 467, 'Disorders of visual pathways in (due to) neoplasm');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Mynte', 8, 'ACTIVE', 468, 'Apraxia following nontraumatic subarachnoid hemorrhage');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skippad', 1, 'ACTIVE', 469, 'Combined forms of age-related cataract, bilateral');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Blogtags', 3, 'ACTIVE', 470, 'Civilian in water injured by military watercraft');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jabbersphere', 10, 'ACTIVE', 471, 'Rheumatoid polyneuropathy with rheumatoid arthritis of hand');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Trunyx', 5, 'ACTIVE', 472, 'Injury of other nerves at ankle and foot level, left leg, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tagpad', 3, 'ACTIVE', 473, 'Burn of third degree of lower leg');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jaloo', 6, 'ACTIVE', 474, 'Partial traumatic transmetacarpal amputation of unspecified hand');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Midel', 5, 'ACTIVE', 475, 'Other mechanical complication of electronic bone stimulator, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Zoombox', 3, 'ACTIVE', 476, 'Explosion of bomb placed during war operations but exploding after cessation of hostilities, military personnel, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Roodel', 4, 'ACTIVE', 477, 'Maternal care for breech presentation, other fetus');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Photobug', 4, 'ACTIVE', 478, 'Corrosion of first degree of unspecified wrist, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Linktype', 3, 'ACTIVE', 479, 'Unspecified dislocation of left ring finger, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Ainyx', 2, 'ACTIVE', 480, 'Activity, other interior property and clothing maintenance');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Bubblebox', 2, 'ACTIVE', 481, 'Struck by shark, initial encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Bluejam', 6, 'ACTIVE', 482, 'Embolism due to internal orthopedic prosthetic devices, implants and grafts');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jamia', 10, 'ACTIVE', 483, 'Unspecified complication of foreign body accidentally left in body following removal of catheter or packing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Gabtune', 5, 'ACTIVE', 484, 'Neonatal jaundice from other hepatocellular damage');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Centizu', 4, 'ACTIVE', 485, 'Displaced fracture of anterior process of unspecified calcaneus, subsequent encounter for fracture with nonunion');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Skiba', 4, 'ACTIVE', 486, 'Dislocation of unspecified parts of lumbar spine and pelvis, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Jetpulse', 1, 'ACTIVE', 487, 'Disorder of penis, unspecified');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Leexo', 4, 'ACTIVE', 488, 'Other disorders of the eye following cataract surgery');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Thoughtstorm', 5, 'ACTIVE', 489, 'Other specified diabetes mellitus with other diabetic ophthalmic complication');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Thoughtmix', 7, 'ACTIVE', 490, 'Urethral caruncle');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tagopia', 8, 'ACTIVE', 491, 'Fibrous dysplasia (monostotic), unspecified upper arm');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Meejo', 2, 'ACTIVE', 492, 'Nondisplaced fracture of lateral condyle of left tibia, initial encounter for open fracture type I or II');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('DabZ', 10, 'ACTIVE', 493, 'Unsatisfactory cytologic smear of anus');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Geba', 3, 'ACTIVE', 494, 'Pedestrian on skateboard injured in collision with railway train or railway vehicle, unspecified whether traffic or nontraffic accident, sequela');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Tavu', 2, 'ACTIVE', 495, 'Galeazzi''s fracture of left radius, subsequent encounter for open fracture type I or II with routine healing');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Thoughtworks', 9, 'ACTIVE', 496, 'Toxic effect of other insecticides, undetermined, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Linkbridge', 4, 'ACTIVE', 497, 'Underdosing of peripheral vasodilators, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Livepath', 8, 'ACTIVE', 498, 'Complete traumatic amputation of left shoulder and upper arm, level unspecified, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Realmix', 9, 'ACTIVE', 499, 'Unspecified superficial injury of left ring finger, subsequent encounter');
insert into PRODUCT (name, brand_id, status, thumbnail, description) values ('Kare', 5, 'ACTIVE', 500, 'Open bite of right back wall of thorax without penetration into thoracic cavity');
